#docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_development
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:migrate && rails s -b 0.0.0.0"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - localstack

  frontend:
    build:
      context: ./frontend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - "4000:3000"
    depends_on:
      - backend

  localstack:
    build:
      context: ./docker/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
